#!/usr/bin/env node
/**
 * OpenSIN-AI repo audit.
 *
 * Queries the GitHub API via `gh repo list` (must be authenticated) and
 * classifies every non-archived repo in the org as one of:
 *   - alive      — real code, recent activity
 *   - scaffold   — small repo with placeholder content
 *   - dead       — 0 KB or equivalent, never filled in
 *   - canonical  — listed in platforms/canonical-repos.json as canonical
 *   - meta       — non-code meta repo (Infra/Template/Biz/website/OpenSIN-overview)
 *
 * Writes registry/SCAFFOLD_AUDIT.md with a grouped markdown table.
 *
 * Usage:
 *   node scripts/audit-repos.js
 *
 * Requires: gh CLI authenticated with read access to OpenSIN-AI.
 */

import { execSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"

const ORG = "OpenSIN-AI"
const OUT = "registry/SCAFFOLD_AUDIT.md"

// Thresholds (in KB)
const DEAD_KB_MAX = 1 // 0 KB only
const SCAFFOLD_KB_MAX = 40 // <=40 KB without real-content markers

function sh(cmd) {
  return execSync(cmd, { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 })
}

function listRepos() {
  const raw = sh(
    `gh repo list ${ORG} --limit 400 --json name,description,diskUsage,pushedAt,isArchived,primaryLanguage`,
  )
  return JSON.parse(raw)
}

function readCanonical() {
  const p = path.join("platforms", "canonical-repos.json")
  if (!fs.existsSync(p)) return new Set()
  const doc = JSON.parse(fs.readFileSync(p, "utf8"))
  const names = new Set()
  const canon = doc?.canonical_repos || {}
  for (const section of Object.values(canon)) {
    if (!section) continue
    if (Array.isArray(section)) {
      for (const e of section) if (e?.name) names.add(e.name)
    } else if (typeof section === "object") {
      for (const e of Object.values(section)) {
        if (Array.isArray(e)) for (const sub of e) if (sub?.name) names.add(sub.name)
        else if (e?.name) names.add(e.name)
      }
    }
  }
  return names
}

function classify(repo, canonicalNames) {
  const name = repo.name
  const kb = Math.round((repo.diskUsage || 0))
  const archived = repo.isArchived
  const isMeta =
    name.startsWith("Infra-SIN-") ||
    name.startsWith("Template-SIN-") ||
    name.startsWith("Biz-SIN-") ||
    name.startsWith("website-") ||
    name === "OpenSIN-overview" ||
    name === "OpenSIN-documentation"

  if (archived) return "archived"
  if (canonicalNames.has(name)) return "canonical"
  if (isMeta) return "meta"
  if (kb <= DEAD_KB_MAX) return "dead"
  if (kb <= SCAFFOLD_KB_MAX) return "scaffold"
  return "alive"
}

function groupOf(name) {
  if (name.startsWith("A2A-SIN-")) return "A2A-SIN-*"
  if (name.startsWith("Team-SIN-")) return "Team-SIN-*"
  if (name.startsWith("Core-SIN-")) return "Core-SIN-*"
  if (name.startsWith("Infra-SIN-")) return "Infra-SIN-*"
  if (name.startsWith("Biz-SIN-")) return "Biz-SIN-*"
  if (name.startsWith("Template-SIN-")) return "Template-SIN-*"
  if (name.startsWith("website-")) return "website-*"
  if (name.startsWith("OpenSIN")) return "OpenSIN*"
  if (name.startsWith("opensin-")) return "opensin-*"
  return "misc"
}

function fmt(repo, cls) {
  const kb = Math.round(repo.diskUsage || 0)
  const lang = repo.primaryLanguage?.name || "—"
  const pushed = (repo.pushedAt || "").split("T")[0] || "—"
  return `| ${repo.name} | ${cls} | ${kb} KB | ${lang} | ${pushed} |`
}

function main() {
  const repos = listRepos()
  const canonicalNames = readCanonical()

  const rows = repos.map((r) => ({ repo: r, cls: classify(r, canonicalNames), group: groupOf(r.name) }))

  const summary = rows.reduce((acc, r) => {
    acc[r.cls] = (acc[r.cls] || 0) + 1
    return acc
  }, {})

  const groups = {}
  for (const r of rows) {
    ;(groups[r.group] ||= []).push(r)
  }

  const now = new Date().toISOString().split("T")[0]
  const lines = []
  lines.push(`# Scaffold + Dead Repo Audit`)
  lines.push("")
  lines.push(`Generated by \`scripts/audit-repos.js\` on ${now}.`)
  lines.push("")
  lines.push(`**Totals:** ${repos.length} repos`)
  lines.push("")
  lines.push("| Classification | Count |")
  lines.push("|---|---:|")
  for (const [k, v] of Object.entries(summary).sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${k} | ${v} |`)
  }
  lines.push("")

  lines.push("## Classification rules")
  lines.push("")
  lines.push("- **archived** — already archived on GitHub.")
  lines.push(
    "- **canonical** — listed in `platforms/canonical-repos.json` under `canonical_repos.*`.",
  )
  lines.push(
    "- **meta** — non-code repos: `Infra-SIN-*`, `Template-SIN-*`, `Biz-SIN-*`, `website-*`, `OpenSIN-overview`, `OpenSIN-documentation`.",
  )
  lines.push("- **dead** — disk usage ≤ 1 KB (empty repo, never filled in). Action: archive.")
  lines.push(
    "- **scaffold** — disk usage ≤ 40 KB and not in one of the above groups. Action: either promote (add real code) or archive.",
  )
  lines.push("- **alive** — anything else. No action needed.")
  lines.push("")

  const groupOrder = [
    "A2A-SIN-*",
    "Team-SIN-*",
    "Core-SIN-*",
    "Infra-SIN-*",
    "Biz-SIN-*",
    "Template-SIN-*",
    "website-*",
    "OpenSIN*",
    "opensin-*",
    "misc",
  ]

  for (const g of groupOrder) {
    const entries = groups[g]
    if (!entries || entries.length === 0) continue
    lines.push(`## ${g} (${entries.length})`)
    lines.push("")
    lines.push("| Repo | Class | Size | Language | Last push |")
    lines.push("|---|---|---:|---|---|")
    entries
      .sort((a, b) => a.repo.name.localeCompare(b.repo.name))
      .forEach((r) => lines.push(fmt(r.repo, r.cls)))
    lines.push("")
  }

  lines.push("## Action items")
  lines.push("")
  const dead = rows.filter((r) => r.cls === "dead").map((r) => r.repo.name)
  const scaffold = rows.filter((r) => r.cls === "scaffold").map((r) => r.repo.name)
  lines.push(`- **Archive immediately** (${dead.length}): ${dead.map((n) => `\`${n}\``).join(", ") || "—"}`)
  lines.push(
    `- **Decide case-by-case** (${scaffold.length}): each scaffold either gets real content in the next sprint or is archived. See individual tracking issues per repo.`,
  )
  lines.push("")
  lines.push("---")
  lines.push("")
  lines.push(
    "Re-run this audit any time the repo topology changes. The output lives at `registry/SCAFFOLD_AUDIT.md` and is the authoritative answer to 'is repo X alive?'.",
  )

  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, lines.join("\n") + "\n")
  console.log(`[audit] wrote ${OUT}`)
  console.log(`[audit] summary:`, summary)
}

main()
